# Generated by Django 4.1.5 on 2023-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("emailbox", models.CharField(max_length=64, verbose_name="邮箱")),
            ],
        ),
    ]
