# Generated by Django 4.1.5 on 2023-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_project",
                    models.CharField(
                        db_index=True, max_length=96, verbose_name="用户_项目名"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=64, verbose_name="任务名称"),
                ),
                ("discription", models.CharField(max_length=500, verbose_name="任务描述")),
                ("text", models.CharField(max_length=5000, verbose_name="处理文本")),
            ],
        ),
    ]
