# Generated by Django 4.1.5 on 2023-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missioninfo",
            name="text",
            field=models.CharField(max_length=5000, verbose_name="上传文本"),
        ),
    ]
