# Generated by Django 4.1.5 on 2023-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mission", "0002_alter_missioninfo_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Missions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_project",
                    models.CharField(
                        db_index=True, max_length=96, verbose_name="用户_项目名"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=64, verbose_name="任务名称"),
                ),
                ("discription", models.CharField(max_length=500, verbose_name="任务描述")),
                ("text", models.CharField(max_length=5000, verbose_name="上传文本")),
            ],
        ),
    ]
