# Generated by Django 4.1.5 on 2023-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(db_index=True, max_length=32, verbose_name="用户名"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=64, verbose_name="项目名称"),
                ),
                ("mood", models.IntegerField(default=1)),
            ],
        ),
    ]
