# Generated by Django 4.1.5 on 2023-04-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0002_datainfo_entityinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_project",
                    models.CharField(
                        db_index=True, max_length=96, verbose_name="用户_项目名"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=64, verbose_name="关系名称"),
                ),
                ("discription", models.CharField(max_length=500, verbose_name="关系描述")),
                (
                    "obj",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="关系主体"
                    ),
                ),
                (
                    "sub",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="关系客体"
                    ),
                ),
            ],
        ),
    ]
